version: 2
workflows:
  version: 2
  flow:
    jobs:
      - publish-service-dev:
          context: babylon
          filters:
            branches:
              only:
                - 7.x
      - publish-service-staging:
          context: babylon
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/
env: &env
  working_directory: ~/project
  docker:
    - image: docker:19.03.14-git
      environment:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk

jobs:
  publish-service-dev:
    <<: *env
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build prerequisites
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" quay.io
            apk add --no-cache make nodejs npm curl openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - run:
          name: Build and push docker image
          command: |
            make build-docker
            make push
  publish-service-staging:
    <<: *env
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build prerequisites
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" quay.io
            apk add --no-cache make nodejs npm curl openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
      - run:
          name: Staging Publish
          command: |
            make publish-staging
