trigger: ['7.x']
pr: none

resources:
  repositories:
    - repository: cd-workflows
      type: github
      endpoint: github
      name: babylonhealth/cd-workflows
      ref: refs/tags/3.5.1

name: $(Build.SourceVersion)

extends:
  template: /azure-yaml/templates/pipelines/single-service-single-env.yml@cd-workflows
  parameters:
    SERVICE_NAME: snowowl
    REGIONS: [dev-internal]
    SLACK_RECIPIENTS: ['#chr-pipelines']
