trigger:
  tags:
    include: ['*.*.*']
pr: none

resources:
  repositories:
    - repository: cd-workflows
      type: github
      endpoint: github
      name: babylonhealth/cd-workflows
      ref: refs/tags/1.3.4

variables:
  - group: BABYLON_PATS
  - name: VERSION
    value: $[variables['Build.SourceBranchName']]

name: $(VERSION)

extends:
  template: /azure-yaml/templates/pipelines/single-service-from-staging.yml@cd-workflows
  parameters:
    STAGING_REGIONS: [staging-global1]
    PREPROD_REGIONS: [preprod-global1]
    PROD_REGIONS: [prod-global1]
    PREPROD_CRP_ROLLBACK_PLAN: Rollback to previous version
    PROD_CRP_ROLLBACK_PLAN: Rollback to previous version
    SLACK_RECIPIENTS: ['#chr-pipelines']
