trigger:
  tags:
    include: ['*.*.*']
pr: none

resources:
  repositories:
    - repository: cd-workflows
      type: github
      endpoint: github
      name: babylonhealth/cd-workflows
      ref: 3.x.x-latest

variables:
  - group: BABYLON_PATS
  - name: VERSION
    value: $[variables['Build.SourceBranchName']]

name: $(VERSION)

extends:
  template: /azure-yaml/templates/pipelines/single-service-from-staging.yml@cd-workflows
  parameters:
    SERVICE: snowowl
    STAGING_REGIONS: [ staging-internal ]
    PREPROD_REGIONS: [ ]
    PROD_REGIONS: [ prod-internal ]
    CRP_ACCOUNTABLE_DEPARTMENT: DATA
    CRP_ACCOUNTABLE_PERSON: gregory.mckay
    PROD_CRP_ROLLBACK_PLAN: Rollback to previous version
    SLACK_RECIPIENTS: [ '#chr-pipelines' ]
