#
# Copyright 2011-2015 B2i Healthcare Pte Ltd, http://b2i.sg
#

authentication:
  type: PROP_FILE

fileAuth:
  users:
    -
      username: snowowl
      password: snowowl

repository:
  port: 2036

# Request execution metrics (response-time, detailed information about transactions, etc.)
metrics:
  enabled: true